export var CurrencyList=[
    {"CurrencyCode":"AED","CurrencyName":"United Arab Emirates Dirham"},
    {"CurrencyCode":"AFN","CurrencyName":"Afghan Afghani"},
    {"CurrencyCode":"ALL","CurrencyName":"Albanian Lek"},
    {"CurrencyCode":"AMD","CurrencyName":"Armenian Dram"},
    {"CurrencyCode":"ANG","CurrencyName":"Netherlands Antillean Guilder"},
    {"CurrencyCode":"AOA","CurrencyName":"Angolan Kwanza"},
    {"CurrencyCode":"ARS","CurrencyName":"Argentine Peso"},
    {"CurrencyCode":"AUD","CurrencyName":"Australian Dollar"},
    {"CurrencyCode":"AWG","CurrencyName":"Aruban Florin"},
    {"CurrencyCode":"AZN","CurrencyName":"Azerbaijani Manat"},
    {"CurrencyCode":"BAM","CurrencyName":"Bosnia-Herzegovina Convertible Mark"},
    {"CurrencyCode":"BBD","CurrencyName":"Barbadian Dollar"},
    {"CurrencyCode":"BDT","CurrencyName":"Bangladeshi Taka"},
    {"CurrencyCode":"BGN","CurrencyName":"Bulgarian Lev"},
    {"CurrencyCode":"BHD","CurrencyName":"Bahraini Dinar"},
    {"CurrencyCode":"BIF","CurrencyName":"Burundian Franc"},
    {"CurrencyCode":"BMD","CurrencyName":"Bermudan Dollar"},
    {"CurrencyCode":"BND","CurrencyName":"Brunei Dollar"},
    {"CurrencyCode":"BOB","CurrencyName":"Bolivian Boliviano"},
    {"CurrencyCode":"BRL","CurrencyName":"Brazilian Real"},
    {"CurrencyCode":"BSD","CurrencyName":"Bahamian Dollar"},
    {"CurrencyCode":"BTN","CurrencyName":"Bhutanese Ngultrum"},
    {"CurrencyCode":"BWP","CurrencyName":"Botswanan Pula"},
    {"CurrencyCode":"BZD","CurrencyName":"Belize Dollar"},
    {"CurrencyCode":"CAD","CurrencyName":"Canadian Dollar"},
    {"CurrencyCode":"CDF","CurrencyName":"Congolese Franc"},
    {"CurrencyCode":"CHF","CurrencyName":"Swiss Franc"},
    {"CurrencyCode":"CLF","CurrencyName":"Chilean Unit of Account UF"},
    {"CurrencyCode":"CLP","CurrencyName":"Chilean Peso"},
    {"CurrencyCode":"CNH","CurrencyName":"Chinese Yuan Offshore"},
    {"CurrencyCode":"CNY","CurrencyName":"Chinese Yuan"},
    {"CurrencyCode":"COP","CurrencyName":"Colombian Peso"},
    {"CurrencyCode":"CUP","CurrencyName":"Cuban Peso"},
    {"CurrencyCode":"CVE","CurrencyName":"Cape Verdean Escudo"},
    {"CurrencyCode":"CZK","CurrencyName":"Czech Republic Koruna"},
    {"CurrencyCode":"DJF","CurrencyName":"Djiboutian Franc"},
    {"CurrencyCode":"DKK","CurrencyName":"Danish Krone"},
    {"CurrencyCode":"DOP","CurrencyName":"Dominican Peso"},
    {"CurrencyCode":"DZD","CurrencyName":"Algerian Dinar"},
    {"CurrencyCode":"EGP","CurrencyName":"Egyptian Pound"},
    {"CurrencyCode":"ERN","CurrencyName":"Eritrean Nakfa"},
    {"CurrencyCode":"ETB","CurrencyName":"Ethiopian Birr"},
    {"CurrencyCode":"EUR","CurrencyName":"Euro"},
    {"CurrencyCode":"FJD","CurrencyName":"Fijian Dollar"},
    {"CurrencyCode":"FKP","CurrencyName":"Falkland Islands Pound"},
    {"CurrencyCode":"GBP","CurrencyName":"British Pound Sterling"},
    {"CurrencyCode":"GEL","CurrencyName":"Georgian Lari"},
    {"CurrencyCode":"GHS","CurrencyName":"Ghanaian Cedi"},
    {"CurrencyCode":"GIP","CurrencyName":"Gibraltar Pound"},
    {"CurrencyCode":"GMD","CurrencyName":"Gambian Dalasi"},
    {"CurrencyCode":"GNF","CurrencyName":"Guinean Franc"},
    {"CurrencyCode":"GTQ","CurrencyName":"Guatemalan Quetzal"},
    {"CurrencyCode":"GYD","CurrencyName":"Guyanaese Dollar"},
    {"CurrencyCode":"HKD","CurrencyName":"Hong Kong Dollar"},
    {"CurrencyCode":"HNL","CurrencyName":"Honduran Lempira"},
    {"CurrencyCode":"HRK","CurrencyName":"Croatian Kuna"},
    {"CurrencyCode":"HTG","CurrencyName":"Haitian Gourde"},
    {"CurrencyCode":"HUF","CurrencyName":"Hungarian Forint"},
    {"CurrencyCode":"IDR","CurrencyName":"Indonesian Rupiah"},
    {"CurrencyCode":"ILS","CurrencyName":"Israeli New Sheqel"},
    {"CurrencyCode":"INR","CurrencyName":"Indian Rupee"},
    {"CurrencyCode":"IQD","CurrencyName":"Iraqi Dinar"},
    {"CurrencyCode":"IRR","CurrencyName":"Iranian Rial"},
    {"CurrencyCode":"ISK","CurrencyName":"Icelandic Krona"},
    {"CurrencyCode":"JEP","CurrencyName":"Jersey Pound"},
    {"CurrencyCode":"JMD","CurrencyName":"Jamaican Dollar"},
    {"CurrencyCode":"JOD","CurrencyName":"Jordanian Dinar"},
    {"CurrencyCode":"JPY","CurrencyName":"Japanese Yen"},
    {"CurrencyCode":"KES","CurrencyName":"Kenyan Shilling"},
    {"CurrencyCode":"KGS","CurrencyName":"Kyrgystani Som"},
    {"CurrencyCode":"KHR","CurrencyName":"Cambodian Riel"},
    {"CurrencyCode":"KMF","CurrencyName":"Comorian Franc"},
    {"CurrencyCode":"KPW","CurrencyName":"North Korean Won"},
    {"CurrencyCode":"KRW","CurrencyName":"South Korean Won"},
    {"CurrencyCode":"KWD","CurrencyName":"Kuwaiti Dinar"},
    {"CurrencyCode":"KYD","CurrencyName":"Cayman Islands Dollar"},
    {"CurrencyCode":"KZT","CurrencyName":"Kazakhstani Tenge"},
    {"CurrencyCode":"LAK","CurrencyName":"Laotian Kip"},
    {"CurrencyCode":"LBP","CurrencyName":"Lebanese Pound"},
    {"CurrencyCode":"LKR","CurrencyName":"Sri Lankan Rupee"},
    {"CurrencyCode":"LRD","CurrencyName":"Liberian Dollar"},
    {"CurrencyCode":"LSL","CurrencyName":"Lesotho Loti"},
    {"CurrencyCode":"LYD","CurrencyName":"Libyan Dinar"},
    {"CurrencyCode":"MAD","CurrencyName":"Moroccan Dirham"},
    {"CurrencyCode":"MDL","CurrencyName":"Moldovan Leu"},
    {"CurrencyCode":"MGA","CurrencyName":"Malagasy Ariary"},
    {"CurrencyCode":"MKD","CurrencyName":"Macedonian Denar"},
    {"CurrencyCode":"MMK","CurrencyName":"Myanma Kyat"},
    {"CurrencyCode":"MNT","CurrencyName":"Mongolian Tugrik"},
    {"CurrencyCode":"MOP","CurrencyName":"Macanese Pataca"},
    {"CurrencyCode":"MRO","CurrencyName":"Mauritanian Ouguiya (pre-2018)"},
    {"CurrencyCode":"MRU","CurrencyName":"Mauritanian Ouguiya"},
    {"CurrencyCode":"MUR","CurrencyName":"Mauritian Rupee"},
    {"CurrencyCode":"MVR","CurrencyName":"Maldivian Rufiyaa"},
    {"CurrencyCode":"MWK","CurrencyName":"Malawian Kwacha"},
    {"CurrencyCode":"MXN","CurrencyName":"Mexican Peso"},
    {"CurrencyCode":"MYR","CurrencyName":"Malaysian Ringgit"},
    {"CurrencyCode":"MZN","CurrencyName":"Mozambican Metical"},
    {"CurrencyCode":"NAD","CurrencyName":"Namibian Dollar"},
    {"CurrencyCode":"NGN","CurrencyName":"Nigerian Naira"},
    {"CurrencyCode":"NOK","CurrencyName":"Norwegian Krone"},
    {"CurrencyCode":"NPR","CurrencyName":"Nepalese Rupee"},
    {"CurrencyCode":"NZD","CurrencyName":"New Zealand Dollar"},
    {"CurrencyCode":"OMR","CurrencyName":"Omani Rial"},
    {"CurrencyCode":"PAB","CurrencyName":"Panamanian Balboa"},
    {"CurrencyCode":"PEN","CurrencyName":"Peruvian Nuevo Sol"},
    {"CurrencyCode":"PGK","CurrencyName":"Papua New Guinean Kina"},
    {"CurrencyCode":"PHP","CurrencyName":"Philippine Peso"},
    {"CurrencyCode":"PKR","CurrencyName":"Pakistani Rupee"},
    {"CurrencyCode":"PLN","CurrencyName":"Polish Zloty"},
    {"CurrencyCode":"PYG","CurrencyName":"Paraguayan Guarani"},
    {"CurrencyCode":"QAR","CurrencyName":"Qatari Rial"},
    {"CurrencyCode":"RON","CurrencyName":"Romanian Leu"},
    {"CurrencyCode":"RSD","CurrencyName":"Serbian Dinar"},
    {"CurrencyCode":"RUB","CurrencyName":"Russian Ruble"},
    {"CurrencyCode":"RUR","CurrencyName":"Old Russian Ruble"},
    {"CurrencyCode":"RWF","CurrencyName":"Rwandan Franc"},
    {"CurrencyCode":"SAR","CurrencyName":"Saudi Riyal"},
    {"CurrencyCode":"SBDf","CurrencyName":"Solomon Islands Dollar"},
    {"CurrencyCode":"SCR","CurrencyName":"Seychellois Rupee"},
    {"CurrencyCode":"SDG","CurrencyName":"Sudanese Pound"},
    {"CurrencyCode":"SEK","CurrencyName":"Swedish Krona"},
    {"CurrencyCode":"SGD","CurrencyName":"Singapore Dollar"},
    {"CurrencyCode":"SHP","CurrencyName":"Saint Helena Pound"},
    {"CurrencyCode":"SLL","CurrencyName":"Sierra Leonean Leone"},
    {"CurrencyCode":"SOS","CurrencyName":"Somali Shilling"},
    {"CurrencyCode":"SRD","CurrencyName":"Surinamese Dollar"},
    {"CurrencyCode":"SYP","CurrencyName":"Syrian Pound"},
    {"CurrencyCode":"SZL","CurrencyName":"Swazi Lilangeni"},
    {"CurrencyCode":"THB","CurrencyName":"Thai Baht"},
    {"CurrencyCode":"TJS","CurrencyName":"Tajikistani Somoni"},
    {"CurrencyCode":"TMT","CurrencyName":"Turkmenistani Manat"},
    {"CurrencyCode":"TND","CurrencyName":"Tunisian Dinar"},
    {"CurrencyCode":"TOP","CurrencyName":"Tongan Pa'anga"},
    {"CurrencyCode":"TRY","CurrencyName":"Turkish Lira"},
    {"CurrencyCode":"TTD","CurrencyName":"Trinidad and Tobago Dollar"},
    {"CurrencyCode":"TWD","CurrencyName":"New Taiwan Dollar"},
    {"CurrencyCode":"TZS","CurrencyName":"Tanzanian Shilling"},
    {"CurrencyCode":"UAH","CurrencyName":"Ukrainian Hryvnia"},
    {"CurrencyCode":"UGX","CurrencyName":"Ugandan Shilling"},
    {"CurrencyCode":"USD","CurrencyName":"United States Dollar"},
    {"CurrencyCode":"UYU","CurrencyName":"Uruguayan Peso"},
    {"CurrencyCode":"UZS","CurrencyName":"Uzbekistan Som"},
    {"CurrencyCode":"VND","CurrencyName":"Vietnamese Dong"},
    {"CurrencyCode":"VUV","CurrencyName":"Vanuatu Vatu"},
    {"CurrencyCode":"WST","CurrencyName":"Samoan Tala"},
    {"CurrencyCode":"XAF","CurrencyName":"CFA Franc BEAC"},
    {"CurrencyCode":"XAG","CurrencyName":"Silver Ounce"},
    {"CurrencyCode":"XAU","CurrencyName":"Gold Ounce"},
    {"CurrencyCode":"XCD","CurrencyName":"East Caribbean Dollar"},
    {"CurrencyCode":"XDR","CurrencyName":"Special Drawing Rights"},
    {"CurrencyCode":"XOF","CurrencyName":"CFA Franc BCEAO"},
    {"CurrencyCode":"XPF","CurrencyName":"CFP Franc"},
    {"CurrencyCode":"YER","CurrencyName":"Yemeni Rial"},
    {"CurrencyCode":"ZAR","CurrencyName":"South African Rand"},
    {"CurrencyCode":"ZMW","CurrencyName":"Zambian Kwacha"},
    {"CurrencyCode":"ZWL","CurrencyName":"Zimbabwean Dollar"},
    
    ]